
version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ecobric
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
  web:
    build: .
    container_name: ecobric_web
    restart: always
    depends_on:
      - db
    # ports:
    #  - "80:80"
    volumes:
      - ./src:/var/www/html

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime_kuma
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./kuma_data:/app/data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - ./grafana_data:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: always
    ports:
      - "9100:9100"

  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: proxy_manager
    restart: always
    ports:
      - '80:80'    # Todas las visitas entran por aquí ahora
      - '443:443'  # El futuro puerto encriptado SSL
      - '81:81'    # Portal web de configuración secreto
    volumes:
      - ./npm_data:/data
      - ./npm_ssl:/etc/letsencrypt

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${PHPMYADMIN_PASSWORD}


volumes:
  portainer_data:
  uptime_kuma_data:
  grafana_data:
  db_data:
