import random
import os
import sys
from datetime import datetime, timedelta

def main():
    nombres_lista = ["Carlos", "Maria", "Alejandro", "Lucia", "Jorge", "Marta", "David", "Laura", "Javier", "Elena", "Daniel", "Ana", "Miguel", "Carmen", "Jose", "Sara"]
    apellidos = ["Garcia", "Rodriguez", "Gonzalez", "Fernandez", "Lopez", "Martinez", "Sanchez", "Perez", "Gomez", "Martin", "Ruiz", "Hernandez", "Diaz", "Moreno", "Alvarez", "Munoz"]
    
    # Hash of 'password' or similar from db
    default_password_hash = "$2y$10$MPKqdCNMbXDECFDK090b2uA8LeObxkFR7tkLl3j1V.YLGOe2tqCza"
    
    # Read product data from db somehow? No, I can't easily read from db without mysql connector, 
    # but I can just hardcode the IDs that were in the ecobric_db.sql file!
    # Valid product IDs and prices based on ecobric_db.sql
    productos = [
        (1, 57.61), (2, 49.05), (3, 30.25), (4, 26.74), (5, 104.49),
        (6, 113.14), (7, 122.82), (8, 208.09), (9, 82.26), (11, 17.31),
        (12, 58.36), (13, 65.95), (14, 21.16), (15, 33.15), (16, 50.75),
        (17, 148.13), (18, 60.79), (19, 66.77), (20, 100.52), (21, 18.15)
    ]
    
    # Valid producto_proveedor IDs based on ecobric_db.sql
    proveedor_data = [
        (1, 1, 46.09, "Black+Decker"), (2, 1, 39.24, "Black+Decker"),
        (3, 1, 24.20, "Black+Decker"), (4, 2, 21.39, "FirstGreen"),
        (5, 3, 83.59, "Graphenstone"), (6, 3, 90.51, "Graphenstone"),
        (7, 3, 98.26, "Graphenstone"), (8, 3, 166.47, "Graphenstone"),
        (9, 4, 65.81, "KEIM"), (11, 4, 13.85, "KEIM"), (12, 4, 46.69, "KEIM"),
        (13, 5, 52.76, "Oropal"), (14, 5, 16.93, "Oropal"),
        (15, 6, 26.52, "Finsa"), (16, 6, 40.60, "Finsa"), (17, 6, 118.50, "Finsa"),
        (18, 6, 48.63, "Finsa"), (19, 6, 53.42, "Finsa"), (20, 6, 80.42, "Finsa")
    ]
    
    now = datetime.now()
    start_date = now - timedelta(days=365)
    
    def random_date_str():
        # returns random datetime string between start_date and now
        delta = now - start_date
        random_days = random.randrange(delta.days)
        random_seconds = random.randrange(86400)
        dt = start_date + timedelta(days=random_days, seconds=random_seconds)
        return dt.strftime('%Y-%m-%d %H:%M:%S')
    
    print("-- Seeding script autogenerated")
    
    print("SET FOREIGN_KEY_CHECKS=0;")
    
    # 1. GENERAR USUARIOS
    usuario_inicio_id = 100  # avoid collision with existing IDs
    print(f"INSERT INTO usuarios (id, rol_id, nombre, email, contrasena, esta_verificado, creado_en) VALUES")
    usuarios_vals = []
    for i in range(200):
        uid = usuario_inicio_id + i
        nombre = f"{random.choice(nombres_lista)} {random.choice(apellidos)} {random.choice(apellidos)}"
        email = f"user_{uid}@ejemplo.com"
        creado = random_date_str()
        usuarios_vals.append(f"({uid}, 2, '{nombre}', '{email}', '{default_password_hash}', 1, '{creado}')")
    
    print(",\n".join(usuarios_vals) + ";")
    
    # 3. GENERAR PEDIDOS
    # Base ID offsets
    pedido_inicio_id = 100
    print(f"INSERT INTO pedidos (id, usuario_id, monto_total, metodo_pago, direccion_envio, estado, creado_en) VALUES")
    pedidos_vals = []
    
    metodos = ['Tarjeta de Crédito', 'PayPal', 'Transferencia Bancaria', 'Bizum']
    direcciones = ['Calle Falsa 123', 'Avenida Siempreviva 742', 'Plaza Mayor 1', 'Gran Via 20', 'Paseo Maritimo 5']
    
    pedido_detalles = [] # pairs of (pedido_id, total_amount)
    all_detalles_vals = []
    
    for i in range(500):
        pid = pedido_inicio_id + i
        uid = random.choice(range(usuario_inicio_id, usuario_inicio_id + 200))
        metodo = random.choice(metodos)
        dir_envio = random.choice(direcciones) + f", Puerta {random.randint(1,20)}"
        creado = random_date_str()
        
        # Generar detalles para este pedido
        num_items = random.randint(1, 4)
        items_c = random.sample(productos, num_items)
        monto_total = 0.0
        for p in items_c:
            prod_id, prod_precio = p[0], p[1]
            cantidad = random.randint(1, 4)
            all_detalles_vals.append(f"({pid}, {prod_id}, {cantidad}, {prod_precio})")
            monto_total += (cantidad * prod_precio)
            
        monto_total = round(monto_total, 2)
        pedidos_vals.append(f"({pid}, {uid}, {monto_total}, '{metodo}', '{dir_envio}', 'PAGADO', '{creado}')")
        
    print(",\n".join(pedidos_vals) + ";")
    
    print("INSERT INTO detalles_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES")
    print(",\n".join(all_detalles_vals) + ";")
    
    # 4. GENERAR GASTOS
    print("INSERT INTO movimientos_inventario (producto_id, tipo_movimiento, cantidad, fecha_movimiento, notas) VALUES")
    gastos_vals = []
    for _ in range(150):
        pr = random.choice(proveedor_data)
        prod_id = pr[0]
        precio_sum = pr[2]
        empresa = pr[3]
        
        cant = random.randint(10, 50)
        creado = random_date_str()
        costo = round(precio_sum * cant, 2)
        notas = f"Compra a {empresa} - Costo: {costo}€"
        gastos_vals.append(f"({prod_id}, 'ENTRADA', {cant}, '{creado}', '{notas}')")
        
    print(",\n".join(gastos_vals) + ";")
    
    print("SET FOREIGN_KEY_CHECKS=1;")

if __name__ == "__main__":
    main()
